### PR TITLE
Django 1.8 Compatibility

### PR DESCRIPTION
**Pull request by johnrtipton**
Fixed some deprecated calls.

### CODE REVIEW

**Comment by jjkester** [comment]
Doesn't this tackle the same issues as #34? If so, why is your solution better?

**Comment by johnrtipton** [comment]
Yes, it looks like we both patched this issue.  It does look like mine has more backwards compatibility checking, so you may want to look into that.  Otherwise, feel free to ignore this request.

**Comment by jjkester** [comment]
Django 1.7 is currently the lowest supported version, so backwards compatibility is not really needed. I think I'll go with the other pull request simply because that one was earlier. Nevertheless, thanks for contributing.

**Comment by johnrtipton** [comment]
Sure, no problem.

**Pull request closed without merging**
