### PR TITLE
add_data to allow injecting additional metadata

### PR DESCRIPTION
**Pull request by agfunder**
m2m and mptt tracking code depends on this small core change

### CODE REVIEW

**Comment by agfunder** [comment]
If this is accepted, I can likely PR the m2m and mptt code as is.
If this is rejected or changed, the m2m and mptt code will need some changes.
So I decided to submit this first.

**Comment by agfunder** [comment]
For example of how I would use add_data, see https://github.com/agfunder/django-auditlog/commit/95e78dd97268e00ff4a268d7f4ee51582e33e07f#diff-f5c12bf42e8cd5ef3a793400e11cd5dfR23

Basically, allows internal code to automatically add some useful metadata into additional_data field.

**Comment by audiolion** [comment]
Ill be able to review this properly in a day or so when I can pull the changes and play around with it

**Comment by agfunder** [comment]
Maybe tests only require change to test_model_without_additional_data

**Comment by audiolion** [comment]
Reviewing this again, I believe the best thing to do is create a third party app that pairs with `django-auditlog` and provides support for `m2m` and `mptt` tracking. This library from the start did not support `m2m` relations.

If you decide to make a third party library extension to `auditlog` I will try and support where I can.

**Pull request closed without merging**
