### PR TITLE
Issue 162 - Update python-dateutil dependency version

### PR DESCRIPTION
**Pull request by charleswhchan**
I actually have a conflict with another package that depends on python-dateutil 2.7 hence upp'ing the max version to 2.8 😄

### CODE REVIEW

**Comment by charleswhchan** [comment]
Can someone tell me what is wrong with the Travis build? It seems the `/master` branch is failing as well? 
https://travis-ci.org/jjkester/django-auditlog

**Comment by charleswhchan** [comment]
Hey @audiolion, are you able to review this PR? Thanks!

**Comment by tcnleung** [comment]
+1 Need this too!

**Comment by charleswhchan** [comment]
Is anyone able to take a look to review the changes? Thanks.

**Pull request closed without merging**
